### ISSUE TITLE
Extra config that uses eslint-plugin-react-hooks

### ISSUE THREAD

**Issue by nicoqh** [suchipi/eslint-config-unobtrusive#6]
Hi!

Thanks for this library.

What do you think about adding another extra config that uses [eslint-plugin-react-hooks](https://github.com/facebook/react/tree/master/packages/eslint-plugin-react-hooks)?

It's an ESLint plugin that enforces [the rules of hooks](https://reactjs.org/docs/hooks-rules.html).

Update: This plugin only contains two rules, so there's probably no need for an "unobtrusive" version. Feel free to close :)

**Comment by suchipi** [comment]
Yeah, I'm gonna close, since people can add those to their config if they want. Thanks for the recommendation, though!
